git:
  remote:
    upstream: 'mongodb/mongo-meta-driver'
    tools: 'mongodb/docs-tools'
  # branches:
  #   manual: 'master'
  #   published:
  #     - 'master'
  #     # the branches/published list **must** be ordered from most to
  #     # least recent release.
project:
  name: 'meta-driver'
  tag: 'meta-driver'
  url: 'http://docs.mongodb.org/meta-driver'
version:
  release: '2.6.5'
  branch: '2.6'
system:
  files:
    - 'push.yaml'
    - 'sphinx.yaml'
    - 'integration.yaml'
  branched: true
assets:
  - branch: master
    path: build/docs-tools
    repository: https://github.com/mongodb/docs-tools.git

paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  images: 'source/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
...